apiVersion: v2
name: cronjob
description: A chart for CronJobs.
icon: https://contino.github.io/intro-k8/images/kubernetes/cronjob.png
version: 2.0.3
appVersion: 2.0.3
type: application
keywords:
  - cronjob
maintainers:
  - name: ellisio
    email: aellis@fluidtruck.com
dependencies:
  - name: common
    repository: https://fluidtruck.github.io/helm-charts
    tags:
      - fluidtruck-common
    version: 1.x.x
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
    version: "11.1.28"
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
    version: "15.7.6"
    condition: redis.enabled
