remote: origin
target-branch: main
debug: true
chart-dirs:
  - charts
excluded-charts:
  - common
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - fluidtruck=https://fluidtruck.github.io/helm-charts
  - prometheus-community=https://prometheus-community.github.io/helm-charts
  - grafana=https://grafana.github.io/helm-charts
  - stable=https://charts.helm.sh/stable
