# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: main
debug: true
chart-dirs:
  - charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - fluidtruck=https://fluidtruck.github.io/helm-charts
helm-extra-args: --timeout 600s
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
