# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: main
debug: true
chart-dirs:
  - charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - bitnami-full=https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  - fluidtruck=https://fluidtruck.github.io/helm-charts
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
