repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  name: helm-charts
  description: Fluid Truck's Helm Charts
  homepage: https://github.com/fluidtruck/helm-charts
  default_branch: main

  has_issues: false
  has_wiki: false
  has_downloads: false

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: false
  delete_brach_on_merge: true

collaborators:
  - username: fluid-devbot
    permission: admin

teams:
  - name: devops
    permission: push

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - boost-security-scan
          - lint
          - test
          - title
      enforce_admins: true
      required_linear_history: true
      restrictions:
        users: [fluid-devbot]
        teams: [devops]
