repository:
  name: helm-charts
  description: Fluid Truck's Helm Charts
  homepage: https://github.com/fluidtruck/helm-charts
  private: false
  default_branch: main

  has_issues: false
  has_wiki: false
  has_downloads: false

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: false
  delete_branch_on_merge: true

  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: actions
    color: F9D0C4
    description: GitHub Actions
  - name: dependabot
    color: FEF2C0
    description: Dependabot
  - name: docker
    color: BFDADC
    description: Docker
  - name: go
    color: C2E0C6
    description: Go

collaborators:
  - username: fluid-devbot
    permission: admin

teams:
  - name: devops
    permission: admin
  - name: security
    permission: admin

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - lint
          - test
          - Semantic Pull Request
      enforce_admins: false
      required_linear_history: true
      restrictions:
        users:
          - fluid-devbot
        teams:
          - devops
