apiVersion: v2
name: dotnet
description: A chart for Dotnet.
icon: https://github.com/dotnet/brand/blob/master/logo/dotnet-logo.svg
version: 1.1.0
appVersion: 1.1.0
type: application
keywords:
  - dotnet
maintainers:
  - name: devops
    email: devops@fluidtruck.com
dependencies:
  - name: common
    repository: https://fluidtruck.github.io/helm-charts
    tags:
      - fluidtruck-common
    version: 1.x.x
  - name: redis
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    tags:
      - redis
    version: "17.15.6"
    condition: redis.enabled
