{{- if eq .Values.loadtest.configmaps.lib "" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-lib
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    loadtest: {{ .Values.loadtest.name | quote }}
data:
  {{- ($.Files.Glob (printf "locustfiles/%s/lib/*" .Values.loadtest.name)).AsConfig | nindent 2 }}
{{- end }}
