{{- $dbHost := include "golang.postgresqlHost" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.strategy }}
  strategy: {{- include "common.tplvalues.render" ( dict "value" .Values.strategy "context" $ ) | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/auth-type: "gcp"
        vault.hashicorp.com/auth-config-type: "iam"
        vault.hashicorp.com/auth-config-service-account: {{ .Values.vault.serviceAccount | quote }}
        vault.hashicorp.com/role: {{ printf "%s-%s-%s" .Values.vault.department .Values.vault.team .Values.env | quote }}
        vault.hashicorp.com/agent-inject-secret-.env.shared: {{ printf "kv/data/%s/%s/shared" .Values.vault.department .Values.vault.team | quote }}
        {{ printf "vault.hashicorp.com/agent-inject-template-.env.shared: |" }}
          {{ printf "{{- with secret \"kv/data/%s/%s/shared\" -}}" .Values.vault.department .Values.vault.team }}
          {{ printf "{{- range $k, $v := .Data.data -}}" }}
          {{ printf "export {{ $k }}=\"{{ $v }}\"" }}
          {{ printf "{{ end -}}" }}
          {{ printf "{{- end -}}" }}
        vault.hashicorp.com/agent-inject-secret-.env: {{ printf "kv/data/%s/%s/%s" .Values.vault.department .Values.vault.team .Values.env | quote }}
        {{ printf "vault.hashicorp.com/agent-inject-template-.env: |" }}
          {{ printf "{{- with secret \"kv/data/%s/%s/%s\" -}}" .Values.vault.department .Values.vault.team .Values.env }}
          {{ printf "{{- range $k, $v := .Data.data -}}" }}
          {{ printf "export {{ $k }}=\"{{ $v }}\"" }}
          {{ printf "{{ end -}}" }}
          {{ printf "{{- end -}}" }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.affinity "context" $ ) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.nodeSelector "context" $ ) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" ( dict "value" .Values.tolerations "context" $ ) | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
      serviceAccountName: {{ template "golang.serviceAccountName" . }}
      {{- if or (eq "true" (include "golang.waitForRedis" .)) (eq "true" (include "golang.waitForPostgresql" .)) }}
      initContainers:
        {{- if eq "true" (include "golang.waitForRedis" .) }}
        - name: wait-for-redis
          image: redis:alpine
          env:
            - name: REDIS_HOST
              value: {{ include "golang.redisHost" . | quote }}
            - name: REDIS_PORT
              value: "6379"
            - name: REDISCLI_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: redis-password
          args:
            - /mnt/redis/wait-for-redis.sh
          volumeMounts:
            - name: wait-for-redis
              mountPath: /mnt/redis
        {{- end }}
        {{- if eq "true" (include "golang.waitForPostgresql" .) }}
        - name: wait-for-postgresql
          image: postgres:alpine
          env:
            - name: DB_HOST
              value: {{ $dbHost }}
            - name: DB_DATABASE
              value: {{ .Values.postgresql.auth.database }}
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username }}
          args:
            - /mnt/postgresql/wait-for-postgresql.sh
          volumeMounts:
            - name: wait-for-postgresql
              mountPath: /mnt/postgresql
        {{- end }}
      {{- end }}
      containers:
        - name: app
          image: {{- include "common.images.image" (dict "imageRoot" .Values.image) | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          securityContext:
            runAsUser: 1001
            runAsNonRoot: true
          env:
            {{- if .Values.redis.enabled }}
            - name: REDIS_HOST
              value: {{ include "golang.redisHost" . | quote }}
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: redis-password
            {{- end }}
            {{- if .Values.postgresql.enabled }}
            - name: DB_HOST
              value: {{ $dbHost }}
            - name: DB_HOST_READ
              value: {{ $dbHost}}
            - name: DB_DATABASE
              value: {{ .Values.postgresql.auth.database }}
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: password
            - name: DB_URL
              value: postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):5432/$(DB_DATABASE)?sslmode=disable
            - name: DB_URL_READ
              value: "$(DB_URL)"
            {{- end }}
            - name: NEW_RELIC_APP_NAME
              value: {{ .Release.Name | quote}}
            - name: ENV
              value: {{ .Values.env }}
            {{- range $key, $value := .Values.envVars }}
            - name: {{ $key }}
              {{- if or (typeIs "string" $value) (typeIs "float64" $value) (typeIs "bool" $value) }}
              value: {{ include "common.tplvalues.render" ( dict "value" $value "context" $ ) | quote }}
              {{- else }}
              {{- include "common.tplvalues.render" ( dict "value" $value "context" $ ) | nindent 14 }}
              {{- end }}
            {{- end }}
          envFrom:
            {{- if .Values.envVarsSecret }}
            {{- if kindIs "string" .Values.envVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" ( dict "value" .Values.envVarsSecret "context" $ ) }}
            {{- else }}
            {{- range $value := .Values.envVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" ( dict "value" $value "context" $ ) }}
            {{- end }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.applicationPort | int }}
            - name: health
              containerPort: {{ .Values.healthPort | int }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port | default "health" }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port | default "health" }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- if or (eq "true" (include "golang.waitForRedis" .)) (eq "true" (include "golang.waitForPostgresql" .)) (.Values.extraVolumes) }}
      volumes:
        {{- if or (eq "true" (include "golang.waitForRedis" .)) }}
        - name: wait-for-redis
          configMap:
            name: {{ template "common.names.fullname" . }}-wait-for-redis
            defaultMode: 0777
        {{- end }}
        {{- if or (eq "true" (include "golang.waitForPostgresql" .)) }}
        - name: wait-for-postgresql
          configMap:
            name: {{ template "common.names.fullname" . }}-wait-for-postgresql
            defaultMode: 0777
        {{- end }}
    {{- end }}
