{{- $dbHost := include "golang.postgresqlHost" . -}}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.fluidtruck.enabled }}
    {{- include "common.labels.fluidtruck" . | nindent 4 }}
    {{- end }}
    {{- if .Values.github.enabled }}
    {{- include "common.labels.github" . | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.github.enabled }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.github.enabled }}
    {{- include "common.annotations.github" . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.strategy }}
  strategy: {{- include "common.tplvalues.render" ( dict "value" .Values.strategy "context" $ ) | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- if .Values.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.github.enabled }}
        {{- include "common.annotations.github" . | nindent 8 }}
        {{- end }}
        {{- if .Values.vault.enabled }}
        vault.hashicorp.com/role: {{ tpl .Values.vault.role . | quote }}
        vault.hashicorp.com/agent-inject: "true"
        {{- range .Values.vault.secrets -}}
        {{- printf "vault.hashicorp.com/agent-inject-secret-%s: \"%s\"" .name .path | nindent 8 }}
        {{- printf "vault.hashicorp.com/agent-inject-template-%s: |" .name | nindent 8 }}
          {{ printf "{{- with secret \"%s\" -}}" .path }}
          {{ .value | default (printf "{{- range $k, $v := .Data.data -}}\n   export {{ $k }}=\"{{ $v }}\"\n{{ end -}}") | indent 10 | trim  }}
          {{ printf "{{- end -}}" }}
        {{- end }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.fluidtruck.enabled }}
        {{- include "common.labels.fluidtruck" . | nindent 8 }}
        {{- end }}
        {{- if .Values.github.enabled }}
        {{- include "common.labels.github" . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "golang.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.affinity "context" $ ) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.nodeSelector "context" $ ) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" ( dict "value" .Values.tolerations "context" $ ) | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      serviceAccountName: {{ template "golang.serviceAccountName" . }}
      {{- if or (eq "true" (include "golang.waitForRedis" .)) (eq "true" (include "golang.waitForPostgresql" .)) }}
      initContainers:
        {{- if eq "true" (include "golang.waitForRedis" .) }}
        - name: wait-for-redis
          image: redis:alpine
          env:
            - name: REDIS_HOST
              value: {{ include "golang.redisHost" . | quote }}
            - name: REDIS_PORT
              value: "6379"
            - name: REDISCLI_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: redis-password
          args:
            - /mnt/redis/wait-for-redis.sh
          volumeMounts:
            - name: wait-for-redis
              mountPath: /mnt/redis
        {{- end }}
        {{- if eq "true" (include "golang.waitForPostgresql" .) }}
        - name: wait-for-postgresql
          image: postgres:alpine
          env:
            - name: DB_HOST
              value: {{ $dbHost }}
            - name: DB_DATABASE
              value: {{ .Values.postgresql.auth.database }}
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username }}
          args:
            - /mnt/postgresql/wait-for-postgresql.sh
          volumeMounts:
            - name: wait-for-postgresql
              mountPath: /mnt/postgresql
        {{- end }}
      {{- end }}
      containers:
        {{- if .Values.swagger.enabled }}
        - name: swagger
          {{- if .Values.swagger.image }}
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.swagger.image ) }}
          imagePullPolicy: {{ .Values.swagger.image.pullPolicy | quote }}
          {{- else }}
          image: {{ template "golang.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - sh
            - -c
            - swagger serve -Fswagger --no-open swagger.json
          {{- end }}
          env:
            - name: PORT
              value: "8081"
          ports:
            - name: swagger
              containerPort: 8081
        {{- end }}
        - name: app
          image: {{ template "golang.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.redis.enabled }}
            - name: REDIS_HOST
              value: {{ include "golang.redisHost" . | quote }}
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: redis-password
            {{- end }}
            {{- if .Values.postgresql.enabled }}
            - name: DB_HOST
              value: {{ $dbHost }}
            - name: DB_HOST_READ
              value: {{ $dbHost}}
            - name: DB_DATABASE
              value: {{ .Values.postgresql.auth.database }}
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: password
            - name: DB_URL
              value: postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):5432/$(DB_DATABASE)?sslmode=disable
            - name: DB_URL_READ
              value: "$(DB_URL)"
            {{- end }}
            {{- range $key, $value := .Values.envVars }}
            - name: {{ $key }}
              {{- if or (typeIs "string" $value) (typeIs "float64" $value) (typeIs "bool" $value) }}
              value: {{ include "common.tplvalues.render" ( dict "value" $value "context" $ ) | quote }}
              {{- else }}
              {{- include "common.tplvalues.render" ( dict "value" $value "context" $ ) | nindent 14 }}
              {{- end }}
            {{- end }}
          envFrom:
            {{- if .Values.envVarsCM }}
            {{- if kindIs "string" .Values.envVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" ( dict "value" .Values.envVarsCM "context" $ ) }}
            {{- else }}
            {{- range $value := .Values.envVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" ( dict "value" $value "context" $ ) }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.envVarsSecret }}
            {{- if kindIs "string" .Values.envVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" ( dict "value" .Values.envVarsSecret "context" $ ) }}
            {{- else }}
            {{- range $value := .Values.envVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" ( dict "value" $value "context" $ ) }}
            {{- end }}
            {{- end }}
            {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.applicationPort }}
            - name: health
              containerPort: {{ .Values.healthPort }}
            {{- range $key, $value := .Values.extraApplicationPorts }}
            - name: {{ $key }}
              containerPort: {{ $value }}
            {{- end }}
          {{- if .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml .Values.extraVolumeMounts | trim | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port | default "health" }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port | default "health" }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.lifecycle }}
          lifecycle: {{- include "common.tplvalues.render" ( dict "value" .Values.lifecycle "context" $ ) | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- if or (eq "true" (include "golang.waitForRedis" .)) (eq "true" (include "golang.waitForPostgresql" .)) (.Values.extraVolumes) }}
      volumes:
        {{- if or (eq "true" (include "golang.waitForRedis" .)) }}
        - name: wait-for-redis
          configMap:
            name: {{ template "common.names.fullname" . }}-wait-for-redis
            defaultMode: 0777
        {{- end }}
        {{- if or (eq "true" (include "golang.waitForPostgresql" .)) }}
        - name: wait-for-postgresql
          configMap:
            name: {{ template "common.names.fullname" . }}-wait-for-postgresql
            defaultMode: 0777
        {{- end }}
        {{- if .Values.extraVolumes }}{{ toYaml .Values.extraVolumes | trim | nindent 8 }}{{ end }}
    {{- end }}
