{{- if and (.Capabilities.APIVersions.Has "secrets.doppler.com/v1alpha1") .Values.doppler.enabled }}
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-{{ .Release.Namespace }}-{{ printf "%s-shared" .Values.doppler.auth.department }}
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: {{ printf "doppler-%s-shared-secret" .Values.doppler.auth.department }}
  managedSecret:
    name: {{ printf "doppler-%s-shared-secret" .Values.doppler.auth.department }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-{{ .Release.Namespace }}-{{ printf "%s-%s-secret" .Values.doppler.auth.department .Values.fluidtruck.env }}
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: {{ printf "doppler-%s-%s-secret" .Values.doppler.auth.department .Values.fluidtruck.env }}
  managedSecret:
    name: {{ printf "doppler-%s-%s-secret" .Values.doppler.auth.department .Values.fluidtruck.env }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-{{ .Release.Namespace }}-{{ printf "%s-shared" .Values.doppler.auth.team }}
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: {{ printf "doppler-%s-shared-secret" .Values.doppler.auth.team }}
  managedSecret:
    name: {{ printf "doppler-%s-shared-secret" .Values.doppler.auth.team }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-{{ .Release.Namespace }}-{{ printf "%s-%s-secret" .Values.doppler.auth.team .Values.fluidtruck.env }}
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: {{ printf "doppler-%s-%s-secret" .Values.doppler.auth.team .Values.fluidtruck.env }}
  managedSecret:
    name: {{ printf "doppler-%s-%s-secret" .Values.doppler.auth.team .Values.fluidtruck.env }}
    namespace: {{ .Release.Namespace }}
{{- end }}
