{{- if .Values.ingress.enabled }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.fluidtruck.enabled }}
    {{- include "common.labels.fluidtruck" . | nindent 4 }}
    {{- end }}
    {{- if .Values.github.enabled }}
    {{- include "common.labels.github" . | nindent 4 }}
    {{- end }}
  {{- if or .Values.ingress.tls.enabled .Values.ingress.annotations .Values.commonAnnotations .Values.github.enabled }}
  annotations:
    {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.issuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuer | quote }}
    {{- end }}
    {{- if .Values.ingress.class }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.ingress.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.github.enabled }}
    {{- include "common.annotations.github" . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  rules:
    - host: {{ include "golang.ingressHostname" . | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" ( dict "serviceName" (include "common.names.fullname" .) "servicePort" "http" "context" $ )  | nindent 14 }}
          {{- if .Values.swagger.enabled }}
          - path: /docs
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: Prefix
            {{- end }}
            backend: {{- include "common.ingress.backend" ( dict "serviceName" (include "common.names.fullname" .) "servicePort" "swagger" "context" $ )  | nindent 14 }}
          - path: /swagger.json
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: Exact
            {{- end }}
            backend: {{- include "common.ingress.backend" ( dict "serviceName" (include "common.names.fullname" .) "servicePort" "swagger" "context" $ )  | nindent 14 }}
          {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ include "golang.ingressRootHostname" . | quote }}
      - {{ printf "*.%s" (include "golang.ingressRootHostname" .) | quote }}
      secretName: {{ printf "%s-tls" .Release.Namespace | replace "." "-" }}
  {{- end }}
{{- end }}
