apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.names.fullname" . }}
  {{- if .Values.serviceAccountAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" .Values.serviceAccountAnnotations "context" $) | nindent 4 }}
  {{- end }}
