apiVersion: v2
name: locust
description: A Helm chart to launch Locust tests.
version: 1.0.0
appVersion: 1.6.0
icon: https://storage.googleapis.com/fluid-tidal-assets-stage/mclovin.jpg
type: application
keywords:
  - fluidtruck
maintainers:
  - name: ellisio
    email: aellis@fluidtruck.com
dependencies:
  - name: common
    repository: https://fluidtruck.github.io/helm-charts
    tags:
      - fluidtruck-common
    version: 1.x.x
