# Default values for locust.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## The Docker image to use.
##
image:
  registry: docker.io
  repository: locustio/locust
  tag: "1.6.0"
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent

## Force target Kubernetes version (using Helm capabilites if not set)
##
kubeVersion:

## String to partially override node.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override node.fullname template
##
# fullnameOverride:

## The load test configuration.
##
loadtest:
  ## The name of your test
  ##
  name: example

  ## The host you will load test
  ##
  hostname: ""

  ## Config Map overrides
  ##
  configmaps:
    lib: ""
    locustfile: ""

## Master Configuration
##
master:
  ## Ingress Configuration
  ##
  ingress:
    ## Hostname to expose the service with.
    ##
    hostname: chart-example.local

  ## Log level. Can be INFO or DEBUG
  ##
  logLevel: INFO

  ## Initial replica count.
  ##
  replicaCount: 1

  ## Resources for the locust worker. Should be configured if you are using HPA.
  ##
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 256Mi
    # requests:
    #   cpu: 500m
    #   memory: 256Mi

## Worker Configuration
##
worker:
  ## HPA Configuration
  ##
  hpa:
    ## Annotations done as key:value pairs
    ##
    annotations: {}

    ## Disabled by default.
    ##
    enabled: false

    ## Replica counts
    ##
    minReplicas: 1
    maxReplicas: 100

    ## Target CPU to initialize scale events.
    ##
    targetCPUUtilizationPercentage: 40

  ## Log level. Can be INFO or DEBUG
  ##
  logLevel: INFO

  ## Initial replica count.
  ##
  replicaCount: 1

  ## Resources for the locust worker. Should be configured if you are using HPA.
  ##
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 256Mi
    # requests:
    #   cpu: 500m
    #   memory: 256Mi
