{{- if and (.Capabilities.APIVersions.Has "cert-manager.io/v1/Certificate") .Values.apiGateway.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-tls" .Release.Name | replace "." "-" }}
spec:
  dnsNames:
  - {{ .Values.apiGateway.hostname | quote }}
  - {{ printf "*.%s" .Values.apiGateway.hostname | quote }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ .Values.apiGateway.tls.issuer | quote }}
  secretName: {{ printf "%s-tls" .Release.Name | replace "." "-" }}
  usages:
  - digital signature
  - key encipherment
{{- end }}
