apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}-master
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: master
    loadtest: {{ .Values.loadtest.name | quote }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: master
      loadtest: {{ .Values.loadtest.name | quote }}
  replicas: {{ .Values.master.replicaCount }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: master
        loadtest: {{ .Values.loadtest.name | quote }}
    spec:
      serviceAccountName: {{ template "common.names.fullname" . }}-master
      containers:
      - name: locust
        image: {{ template "locust.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
          - name: http
            containerPort: 8089
          - name: p1
            containerPort: 5557
          - name: p2
            containerPort: 5558
        env:
          - name: LOCUST_HOST
            value: "{{ .Values.loadtest.hostname }}"
        command:
          - /usr/local/bin/locust
        args:
          - --master
          - --locustfile=/mnt/locust/main.py
          - --host={{ .Values.loadtest.hostname }}
          - --loglevel={{ .Values.master.logLevel }}
        livenessProbe:
          periodSeconds: 30
          initialDelaySeconds: 10
          timeoutSeconds: 30
          failureThreshold: 2
          httpGet:
            path: /
            port: http
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 2
          httpGet:
            path: /
            port: http
        {{- if .Values.master.resources }}
        resources:
          {{- toYaml .Values.master.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
          - name: lib
            mountPath: /mnt/locust/lib
          - name: locustfile
            mountPath: /mnt/locust
      volumes:
        - name: lib
          configMap:
            name: {{ template "locust.configmaps.lib" . }}
        - name: locustfile
          configMap:
            name: {{ template "locust.configmaps.locustfile" . }}
