apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.names.fullname" . }}-master
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: master
    loadtest: {{ .Values.loadtest.name | quote }}
