{{- if and (.Capabilities.APIVersions.Has "getambassador.io/v3alpha1/TLSContext") .Values.ingress.enabled .Values.ingress.tls.enabled (eq .Values.ingress.class "ambassador") }}
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.fluidtruck.enabled }}
    {{- include "common.labels.fluidtruck" . | nindent 4 }}
    {{- end }}
    {{- if .Values.github.enabled }}
    {{- include "common.labels.github" . | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.github.enabled }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.github.enabled }}
    {{- include "common.annotations.github" . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  hosts:
    - {{ include "dotnet.ingressHostname" . | quote }}
  secret: {{ printf "%s-tls" .Release.Namespace | replace "." "-" }}
{{- end }}
