apiVersion: v2
name: golang
description: A chart for Golang.
icon: https://golang.org/lib/godoc/images/go-logo-blue.svg
version: 10.0.0
appVersion: 10.0.0
type: application
keywords:
  - go
maintainers:
  - name: devops
    email: devops@fluidtruck.com
dependencies:
  - name: common
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    tags:
      - common
    version: 2.13.2
  - name: postgresql
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    tags:
      - postgresql
    version: "13.0.0"
    condition: postgresql.enabled
  - name: redis
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    tags:
      - redis
    version: "18.1.1"
    condition: redis.enabled
