apiVersion: v2
name: golang
description: A chart for Golang.
icon: https://golang.org/lib/godoc/images/go-logo-blue.svg
version: 9.2.4
appVersion: 9.2.4
type: application
keywords:
  - go
maintainers:
  - name: devops
    email: devops@fluidtruck.com
dependencies:
  - name: common
    repository: https://fluidtruck.github.io/helm-charts
    tags:
      - fluidtruck-common
    version: 1.x.x
  - name: postgresql
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    tags:
      - postgresql
    version: "11.1.28"
    condition: postgresql.enabled
  - name: redis
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    tags:
      - redis
    version: "15.7.6"
    condition: redis.enabled
