apiVersion: v2
name: golang
description: A chart for Golang.
icon: https://golang.org/lib/godoc/images/go-logo-blue.svg
version: 2.0.2
appVersion: 2.0.2
type: application
keywords:
  - go
maintainers:
  - name: ellisio
    email: aellis@fluidtruck.com
dependencies:
  - name: common
    repository: https://fluidtruck.github.io/helm-charts
    tags:
      - fluidtruck-common
    version: 1.x.x
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
    version: "10.9.1"
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
    version: "14.8.8"
    condition: redis.enabled
