# Default values for golang.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## The environment being installed to.
##
env: dev

## The image version
##
image:
  registry: ghcr.io
  repository: fluidtruck/go-demo
  tag: latest
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

## Force target Kubernetes version (using Helm capabilites if not set)
##
kubeVersion:

## String to partially override golang.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override golang.fullname template
##
# fullnameOverride:

## Specify the number of replicas for the application
##
replicaCount: 1

## Specify the port where your application will be running
##
applicationPort: 8090

## Specify the port where you health checks will be running
##
healthPort: 8080

## Affinity for pod assignment. Evaluated as a template.
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Node labels for pod assignment. Evaluated as a template.
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment. Evaluated as a template.
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: {}

## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}

## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
##
livenessProbe:
  enabled: true
  path: '/'
  # port: 8090
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  path: '/'
  # port: 8090
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

## An array to add extra env vars
## For example:
##
envVars: {}
  # BEARER_AUTH: true
  # OTHER_VAR: "foo"
  # SOME_PASSWORD:
  #   valueFrom:
  #     secretKeyRef:
  #       name: some-ref
  #       key: redis-password

## Secret with extra environment variables
##
envVarsSecret:

## The containers' resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits: {}
  #   cpu: 100m
  #   memory: 128Mi
  requests: {}
  #   cpu: 100m
  #   memory: 128Mi

## Vault settings for secrets
##
vault:
  enabled: false
  department: engineering
  team: team-name
  serviceAccount: soma-sa@some-project.iam.gserviceaccount.com

## The Deployment update strategy
## ref: https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/deployment-v1/#DeploymentSpec
##
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 0

## Service parameters
##
service:
  ## App Protocol
  ##
  ## - http
  ## - grpc (Default)
  ##
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol
  ##
  appProtocol: grpc

  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}

## API Gateway
##
gateway:
  ## Set to true to enable api gateway endpoint.
  ##
  enabled: false

  ## Set this to the hostname you want to use.
  ##
  hostname: ""

  ## The URL prefix identifying your resource.
  ##
  prefix: ""

  ## Extra annotations.
  ##
  annotations: {}

## Configure the hpa resource that enables autoscaling of the deployment
## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
##
hpa:
  ## Set to true to enable hpa record generation
  ##
  enabled: false

  ## The minimum number of replicas to maintain
  ##
  minReplicas: 1

  ## The maximum number of replicas to maintain
  ##
  maxReplicas: 5

  ## The target CPU utilization percentage
  ##
  targetCPUUtilizationPercentage: 80

  ## HPA annotations done as key:value pairs
  ##
  annotations: {}

## Pod Disruption Budget
## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
##
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  # maxUnavailable: 1

## Configure the postgresql service
## ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
##
postgresql:
  enabled: false
  wait: false
  auth:
    username: postgresql
    password: postgresql
    database: postgresql
  image:
    tag: 14.9.0-debian-11-r55

## Configure the redis service
## ref: https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml
##
redis:
  enabled: false
  wait: false
  architecture: standalone
  auth:
    password: redis

## Configure the service account
##
serviceAccount:
  create: false

  ## Define a custom service account name
  ##
  name: ""

  ## Additional k8s Service Account annotations
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  ## For example, to add a Workload identity binding
  annotations: {}
    # iam.gke.io/gcp-service-account: example-sa@some-project.iam.gserviceaccount.com
