name: pr

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct-lint.yaml

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          # We need to support K8S v1.18 until we're off the old infra.
          cluster_name: kind
          node_image: kindest/node:v1.18.19

      - name: Scaffold Kind Config
        run: |
          mkdir /tmp/kind
          cat <<EOF > /tmp/kind/config.json
          {
            "auths": { "us-central1-docker.pkg.dev": {} }
          }
          EOF

      - name: Authenticate With Google
        uses: docker/login-action@v1
        env:
          DOCKER_CONFIG: /tmp/kind
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.ARTIFACT_REGISTRY_SERVICE_ACCOUNT }}

      - name: Copy Docker Config to Kind
        run: |
          for node in $(kind get nodes --name "kind"); do
            node_name=${node#node/}
            docker cp /tmp/kind/config.json "${node_name}:/var/lib/kubelet/config.json"
            docker exec "${node_name}" systemctl restart kubelet.service
          done

      - name: Run chart-testing (install)
        run: ct install --config .github/ct-install.yaml
