name: release

on:
  push:
    branches:
      - main

jobs:
  chart-releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Previous Runs
        uses: ahmadnassri/action-workflow-queue@v1

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add fluidtruck https://fluidtruck.github.io/helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
